### ISSUE TITLE
Migrate to Vue 3

### ISSUE THREAD

**Issue by MrTimscampi** [jellyfin/jellyfin-vue#113]
This issue is meant to track what's needed in order for a complete move to Vue 3.

**Earliest expected date: Q3 2021**

## Dependencies

* [x] Vue 3
* [ ] Nuxt 3 (https://github.com/nuxt/nuxt.js/issues/5708 - Open beta in Q2 2021)
* [ ] Vuetify 3 ([Q3 2021](https://vuetifyjs.com/en/introduction/roadmap/#in-development))
* [x] [Vuex 4](https://github.com/vuejs/vuex/releases/tag/v4.0.0)
* [x] vue-i18n ([v9](https://blog.intlify.dev/posts/vue-i18n-9.html))
* [ ] ~~nuxt-auth (Dependent on Nuxt 3)~~
* [ ] nuxt-axios (Dependent on Nuxt 3)
* [ ] nuxt-pwa (Dependent on Nuxt 3)
* [ ] nuxt-i18n (Dependent on vue-i18n and Nuxt 3)
* [ ] nuxt-date-fns (Dependent on Nuxt 3)
* [ ] ~~nuxt-vuex-localstorage (Dependent on Nuxt 3)~~
* [ ] vue-virtual-scroller ~~(Potentially replaced with custom solution. See #274)~~. Replacement in the works in #606
* [x] ~~VueperSlides~~ ~~To be replaced with [Swiper](https://swiperjs.com/vue/)~~ Replaced in #412
* [x] eslint-plugin-vue 7.0.0
* [ ] vue-test-utils 2.0.0 ([RC-8](https://github.com/vuejs/vue-test-utils-next/releases))
* [x] vue-axe

**Manually-required code changes are, as of yet, unknown. This issue will be updated as information becomes available.**

**Comment by ferferga** [comment]
This might be useful to have at a hand:
 https://github.com/vuejs/awesome-vue/issues/3544

**Comment by ThibaultNocchi** [comment]
Still useful

**Comment by timberzzman** [comment]
As it said on the website, _Is Nuxt 3 Ready_ has been archived.

This is the new nuxt modules compilation : [https://modules.nuxtjs.org/](https://modules.nuxtjs.org/)

**Comment by maicss** [comment]
Any development plan?

**Comment by NebelNidas** [comment]
Nuxt 3.0 stable is out now, if anyone is still interested in this rewrite

**Comment by Extarys** [comment]
nuxt-i18n beta seems to work nicely too with nuxt 3.

**Comment by ferferga** [comment]
@NebelNidas @Extarys Please check open PRs first: https://github.com/jellyfin/jellyfin-vue/pull/1812
