### ISSUE TITLE
List of features

### ISSUE THREAD

**Issue by MrTimscampi** [jellyfin/jellyfin-vue#115]
This is meant to be a somewhat exhaustive list of features to implement in order to consider this client "production-ready". It aims to match (but rework) the feature set of the current Jellyfin web client.

Feel free to claim a feature by opening an issue or a PR to discuss implementation, UI, UX, and usability.

**When re-implementing a feature, please don't blindly copy what is done on Jellyfin web. We would like to take this opportunity to rethink everything, with a particular focus on accessibility, user experience and usability.**

*Note: claimed features are expected to be implemented (or at least started) by the person claiming them. Do not open a discussion for features you do not intend to work on.*

---

## General

* [ ] Add Dialog/Modal system
* [x] Add backdrop support (#105)

## Authentication, login and server selection

* [x] User authentication
* [x] Login screen
* [ ] Automatic login/Remember me
* [ ] Quick login with visible users
* [ ] Server selection
* [ ] Remember previous servers
* [ ] Server detection (Using a json config file)
* [ ] Server manifest checking
* [ ] Add Quick Connect pin support

## Home

* [x] Continue watching
* [x] Continue listening
* [x] Next up
* [x] Latest
* [ ] Live TV
* [ ] Active recordings
* [ ] My media
* [x] Pull home section list from the server
* [x] Provide default sections
* [ ] Provide a skeleton loader for sections

## Libraries

* [x] List libraries for navigation
* [x] Navigate libraries
* [x] Navigate folders
* [x] Provide a skeleton loader for libraries
* [ ] Allow to switch between pagination and infinite scroll
* [x] Implement a virtual scroller (#119)
* [ ] Add sorting
* [ ] Add filters
* [ ] Add view modes (Movies, Collections, Album Artist, Track, etc)

## Item details

* [x] Implement a basic details page
* [x] Add season list
* [x] Add related items
* [ ] Add extras
* [ ] Add actors
* [ ] Add metadata editor
* [ ] Add image editor
* [ ] Add item identification (#114)

## Playback

* [x] Provide a mechanism for platform detection
* [x] Generate a playback profile
* [ ] Add video playback support (#74)
* [ ] Add audio playback support
* [ ] Add PDF playback support
* [ ] Add EPUB playback support
* [ ] Add CBZ/CBR playback support
* [ ] Add playback manager (Handle playlists, playing multiple items, etc)
* [ ] Add "Play on" feature
* [ ] Add Chromecast support
* [ ] Add playback session reporting
* [ ] Add playback resume support
* [ ] Add subtitle support
* [ ] Add audio track switching support
* [ ] Add forward/back buttons to video player
* [ ] Add next/previous track to video player
* [ ] Add playback speed control to video player
* [ ] Add SyncPlay support
* [ ] Add Up next dialog

## Live TV

* [ ] Add channel listing
* [ ] Add guide
* [ ] Add recordings management

## User settings

* [ ] Add user account settings (#63)
* [ ] Add home screen settings
* [ ] Add playback settings
* [ ] Add subtitle settings
* [ ] Add display settings

## Metadata editor

* [ ] Add folder list
* [ ] Add metadata editor

## Server settings

* [ ] Add dashboard (#63)
* [ ] Add general settings
* [ ] Add users settings
* [ ] Add libraries
* [ ] Add library display settings
* [ ] Add NFO settings
* [ ] Add transcoding settings
* [ ] Add resume settings
* [ ] Add streaming settings
* [ ] Add activity log
* [ ] Add DLNA settings
* [ ] Add DLNA profile editor
* [ ] Add TV tuner settings
* [ ] Add DVR settings
* [ ] Add networking settings
* [ ] Add API keys management
* [ ] Add logs viewer
* [ ] Add notification settings
* [ ] Add plugins list
* [ ] Add plugin configuration
* [ ] Add plugin installation
* [ ] Add repository management
* [ ] Add scheduled task configuration

**Comment by Dec-F** [comment]
> Metadata editor
 Add folder list
 Add metadata editor

I can do metadata editing, starting from the folder list

**Comment by Camc314** [comment]
> > Metadata editor
> > Add folder list
> > Add metadata editor
> 
> I can do metadata editing, starting from the folder list

I think @MrTimscampi is working on a metadata editor (#68)

**Comment by MrTimscampi** [comment]
So, there are two metadata editors.

The one in #68 is the single-item editor, in the item menu.

The one in the "metadata editor" section is the one with the folder list and such.

Obviously, there is overlap between the two. The form itself would likely be a shared component.

I can hand over the existing metadata editor PR, if wanted, so that you can work on setting something up @Dec-F. I have enough stuff to work on anyway, and too little time to do it :yum:

**Comment by MrTimscampi** [comment]
I also have a lot of concerns about the UI/UX part of the folder-based metadata editor.

I know it's a useful feature and all, but I haven't been able to think of a design that makes sense, it fully responsive and with good UX.

It's probably the part that needs the most re-design work in everything we're bringing over, because the existing one is terrible in all aspects.

**Comment by Dec-F** [comment]
@MrTimscampi You can transfer it to me, I will do the rest, UI/UX issues, then I will open an issue to discuss the details

**Comment by Dec-F** [comment]
@MrTimscampi You can pass it on to me and I will do the rest. UI/UX issues Next I will open an issue to discuss the details

**Comment by MrTimscampi** [comment]
Cool, I closed the open one, it's all yours :smiley:

**Comment by MrTimscampi** [comment]
Closing this in favor of single issues. More will be created as we go along.
