### ISSUE TITLE
Implement the new Items store in all the client

### ISSUE THREAD

**Issue by MrTimscampi** [jellyfin/jellyfin-vue#980]
This issue is meant to track the implementation of the items store in the rest of the app.

Please claim something if you're starting to work on it, to prevent multiple people working on it.

See #801 for more information behind the idea for the items store and how stuff should be organized around it.

* [x] RelatedItems (#994)
* [ ] MetadataEditor
* [ ] HomeHeader (@MrTimscampi)
* [ ] TrackList
* [ ] library/_viewId
* [ ] metadata
* [ ] store/homeSections (@MrTimscampi)
* [ ] store/tvShows (Has to be refactored according to #801)
* [ ] store/userViews (Has to be refactored according to #801)
* [x] translateItemsForPlayback (This should include a refactor of the playbackManager store according to #801) (@MrTimscampi #1008)
